# Generated by Django 2.2.4 on 2020-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0015_ques_istest'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.FileField(upload_to='saved_models/')),
            ],
        ),
    ]
