# Generated by Django 2.2.4 on 2020-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0016_saved_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_models',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
