# Generated by Django 2.2.4 on 2020-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0017_auto_20200607_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studrecords',
            name='DT',
        ),
        migrations.AddField(
            model_name='studrecords',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studrecords',
            name='sum_click',
            field=models.IntegerField(default=0),
        ),
    ]
