# Generated by Django 2.2.4 on 2020-06-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0018_auto_20200616_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questr',
            name='qtype',
        ),
        migrations.CreateModel(
            name='practqn_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.ques')),
            ],
        ),
    ]
