# Generated by Django 2.2.4 on 2020-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0021_practqn_attempt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questr',
            name='islive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='islive',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='attempt',
        ),
    ]
