# Generated by Django 2.2.4 on 2020-06-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0022_auto_20200628_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='extqnr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DT', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.List')),
            ],
        ),
        migrations.CreateModel(
            name='ext_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('mm', models.IntegerField()),
                ('extqnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.extqnr')),
            ],
        ),
    ]
