# Generated by Django 2.2.4 on 2020-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0024_auto_20200630_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='practqn_attempt',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
