# Generated by Django 2.2.4 on 2020-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0025_practqn_attempt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='courseid',
            field=models.IntegerField(default=-1),
        ),
    ]
