# Generated by Django 2.2.4 on 2020-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0026_ques_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='feedback',
            field=models.TextField(default='Default feedback'),
        ),
        migrations.AddField(
            model_name='ques',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='quesimage/'),
        ),
    ]
