# Generated by Django 2.2.4 on 2020-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0027_auto_20200717_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
