# Generated by Django 2.2.4 on 2020-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0029_saved_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='practqn_attempt',
            name='time_taken',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questr',
            name='time_taken',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
