# Generated by Django 2.2.4 on 2021-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0031_auto_20201026_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='islive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='links',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
