# Generated by Django 2.2.4 on 2021-07-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0034_assignments_islive'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentPractScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.List')),
            ],
        ),
    ]
