# Generated by Django 2.2.4 on 2021-08-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Link2', '0036_practqn_attempt_resetted'),
    ]

    operations = [
        migrations.CreateModel(
            name='practSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('score_easy', models.FloatField()),
                ('score_med', models.FloatField()),
                ('score_hard', models.FloatField()),
                ('quesCount_easy', models.IntegerField()),
                ('quesCount_med', models.IntegerField()),
                ('quesCount_hard', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Link2.List')),
            ],
        ),
    ]
